### PR TITLE
$currentClass preg_match and renderMultiTVFormElement bugfix

### PR DESCRIPTION
**Pull request by ricardo-lewis**
$currentClass preg_match is now non-greedy
renderMultiTVFormElement now uses $type for CSS class name

### CODE REVIEW

**Comment by Jako** [comment]
The preg change is fine, but why did you change from fieldname to type?

**Comment by ricardo-lewis** [comment]
I did it specifically for the date type. The javascript required a class of "mtv_date" in order to apply the Datepicker.

https://github.com/Jako/multiTV/blob/8e049c0d70726b7c3ca22c23e3f60ce7c831562f/assets/tvs/multitv/js/multitv.js#L240

**Comment by Jako** [comment]
I am not sure why this line contains `.mtv_date`. It was changed here: https://github.com/Jako/multiTV/commit/8a0c68271691674ab9551e49de5da77a2ad04af7

It should be `.mtvDatePicker` according to https://github.com/Jako/multiTV/blob/ba8012cfef8e90a499207a947b2938a972702bfa/assets/tvs/multitv/includes/multitv.class.php#L413-L415

But maybe the current date input does not contain the `DatePicker` class anymore and @dmi3yy patched it wrong. 

Could you look which class a date template variable in Evo 1.3 is used and add a replacement after line 414 in https://github.com/Jako/multiTV/blob/ba8012cfef8e90a499207a947b2938a972702bfa/assets/tvs/multitv/includes/multitv.class.php.

**Comment by ricardo-lewis** [comment]
The example code is from the latest 2.11 Release, which is what I'm using in production, so this fix is for people using that version.

Line 414 does add the class **mtvDatePicker** but in 2.11 the Javascript was not looking for that class, it was looking for **.mtv_date** and the class name fed to **renderMultiTVFormElement()** was (and still is) **'inline mtv_' . $fieldname** which means the field name always had to be "date" in order for the Datepicker JS to work.

My solution above chose to fix the PHP side, rather than the JS side.

**Comment by Jako** [comment]
The example code is from the latest 2.1.1 release of MultiTV on https://github.com/extras-evolution/multiTV 

In this repository it was not changed: https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/js/multitv.js#L218

So please say thanks to @dmi3yy for the 'improvement'.

**Comment by dmi3yy** [comment]
Write here: https://github.com/extras-evolution/multiTV/

**Comment by Jako** [comment]
Where?

**Comment by ricardo-lewis** [comment]
Thanks @dimi33y I'll submit the pull request if your code needs it

**Pull request closed without merging**
