### PR TITLE
Added Duplicate-Button for "datatable"-mode, allow different TinyMCE4-themes for richtext

### PR DESCRIPTION
**Pull request by Deesen**

### CODE REVIEW

**Comment by Jako** [comment]
Hi, it would be nice, if you prepare multiple branches for solving different issues/features and do a PR with these branches. You could merge those branches into your fork and I don't have to cherry pick them.

The check for old mootools commit is (maybe) not needed. multiTV uses a jquery ui datetimepicker before patch (https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/js/jquery-ui-timepicker-addon.js). So it would be better not to include that script file with Evo 1.1 and change the timeFormat on base of the Evo version.

**Comment by Deesen** [comment]
Hi and sry, I will prepare several branches then.

Reg. the old/new datepicker I am not sure how to solve it otherwise. Without this commit, timeformat is "HH:mm:ss" which the new datepicker cannot interpret. So when picking a date it outputs "29-08-2016 HH:mm:ss".

**Comment by Deesen** [comment]
First timer for me splitting multiple commits into multiple branches afterwards like this. Hope everything is ok.

**Comment by Jako** [comment]
Thanks, will look through them the next week.

**Pull request closed without merging**
